-- =====================================================================
-- usp_RunPayroll
--
-- Generates payroll for a given Month/Year:
--   1. Validates inputs
--   2. Prevents duplicate payroll generation (immutability rule)
--   3. Calculates Gross Pay / PF / Professional Tax / Net Pay per employee
--   4. Persists the run + per-employee detail rows atomically
--   5. Returns the generated payroll summary
--
-- Business formulas (must match PayrollCalculator.cs in the API):
--   Gross Pay  = (Basic Salary / Total Working Days) * Days Present
--   PF         = 12% of Basic Salary
--   Prof. Tax  = flat 200
--   Net Pay    = Gross Pay - PF - Professional Tax
-- =====================================================================
CREATE OR ALTER PROCEDURE usp_RunPayroll
    @Month INT,
    @Year  INT
AS
BEGIN
    SET NOCOUNT ON;

    -- -----------------------------------------------------------------
    -- 1. Input validation
    --    Defends the procedure against bad input even if it's ever
    --    called directly (SSMS, a job, another app) and not just via
    --    our API's [Range] - validated DTO.
    -- -----------------------------------------------------------------
    IF (@Month IS NULL OR @Month < 1 OR @Month > 12)
    BEGIN
        RAISERROR('Month must be between 1 and 12.', 16, 1);
        RETURN;
    END

    IF (@Year IS NULL OR @Year < 2000 OR @Year > 2100)
    BEGIN
        RAISERROR('Year must be a valid 4-digit year between 2000 and 2100.', 16, 1);
        RETURN;
    END

    -- -----------------------------------------------------------------
    -- 2. Duplicate prevention (THE core immutability guard)
    --    Payroll runs cannot be edited, deleted, or regenerated once
    --    created. This is the authoritative, server-side check - even
    --    if the API's own pre-check (PayrollService.ExistsAsync) were
    --    ever bypassed or raced by a concurrent request, this statement
    --    (backed by the UNIQUE constraint on PayrollRuns(Month, Year))
    --    is the final word.
    -- -----------------------------------------------------------------
    IF EXISTS (SELECT 1 FROM PayrollRuns WHERE Month = @Month AND Year = @Year)
    BEGIN
        RAISERROR('Payroll for %d/%d has already been generated and cannot be run again.', 16, 1, @Month, @Year);
        RETURN;
    END

    -- -----------------------------------------------------------------
    -- 3. Guard against generating an empty payroll run
    --    If no active employee has an attendance record for this period,
    --    there is nothing to pay - fail clearly instead of silently
    --    creating a PayrollRuns header with zero detail rows.
    -- -----------------------------------------------------------------
    IF NOT EXISTS (
        SELECT 1
        FROM Employees e
        INNER JOIN Attendance a ON a.EmployeeId = e.EmployeeId
        WHERE e.IsActive = 1
          AND a.Month = @Month
          AND a.Year = @Year
    )
    BEGIN
        RAISERROR('No active employees with attendance records found for %d/%d. Payroll run aborted.', 16, 1, @Month, @Year);
        RETURN;
    END

    -- -----------------------------------------------------------------
    -- 4. Calculate and persist - wrapped in a transaction so the header
    --    row (PayrollRuns) and every detail row (PayrollRunDetails) are
    --    committed together, or not at all. A partially-generated
    --    payroll run would be worse than no run at all.
    -- -----------------------------------------------------------------
    DECLARE @PayrollRunId INT;

    BEGIN TRANSACTION;

    BEGIN TRY
        INSERT INTO PayrollRuns (Month, Year, RunDate, IsFinalized)
        VALUES (@Month, @Year, SYSUTCDATETIME(), 1);

        -- SCOPE_IDENTITY() returns the identity value generated by the
        -- INSERT immediately above, in the current scope - safer than
        -- @@IDENTITY, which can return an identity from an unrelated
        -- trigger firing on the same connection.
        SET @PayrollRunId = SCOPE_IDENTITY();

        -- One set-based INSERT...SELECT computes and persists every
        -- employee's pay in a single statement - far more efficient
        -- than looping row-by-row (RBAR - "Row By Agonizing Row").
        INSERT INTO PayrollRunDetails
            (PayrollRunId, EmployeeId, BasicSalary, WorkingDays, DaysPresent,
             GrossPay, PFDeduction, ProfessionalTax, NetPay)
        SELECT
            @PayrollRunId,
            e.EmployeeId,
            e.BasicSalary,
            a.TotalWorkingDays,
            a.DaysPresent,
            ROUND(e.BasicSalary / a.TotalWorkingDays * a.DaysPresent, 2)   AS GrossPay,
            ROUND(e.BasicSalary * 0.12, 2)                                 AS PFDeduction,
            200.00                                                         AS ProfessionalTax,
            ROUND(e.BasicSalary / a.TotalWorkingDays * a.DaysPresent, 2)
                - ROUND(e.BasicSalary * 0.12, 2) - 200.00                  AS NetPay
        FROM Employees e
        INNER JOIN Attendance a
            ON a.EmployeeId = e.EmployeeId
           AND a.Month     = @Month
           AND a.Year      = @Year
        WHERE e.IsActive = 1;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        -- Re-throw the original error (preserves message, severity, line
        -- number) so the caller sees exactly what went wrong in SQL Server.
        THROW;
    END CATCH;

    -- -----------------------------------------------------------------
    -- 5. Return the generated payroll summary
    --    The API re-queries via EF Core for its response shape (see
    --    PayrollRepository.ExecuteRunPayrollAsync), but returning the
    --    result set here makes the procedure independently useful and
    --    verifiable - e.g. a DBA running it directly in SSMS immediately
    --    sees what was generated.
    -- -----------------------------------------------------------------
    SELECT
        pr.PayrollRunId,
        pr.Month,
        pr.Year,
        pr.RunDate,
        pr.IsFinalized,
        e.EmployeeId,
        e.EmployeeCode,
        e.FullName,
        prd.BasicSalary,
        prd.WorkingDays,
        prd.DaysPresent,
        prd.GrossPay,
        prd.PFDeduction,
        prd.ProfessionalTax,
        prd.NetPay
    FROM PayrollRuns pr
    INNER JOIN PayrollRunDetails prd ON prd.PayrollRunId = pr.PayrollRunId
    INNER JOIN Employees e           ON e.EmployeeId     = prd.EmployeeId
    WHERE pr.PayrollRunId = @PayrollRunId
    ORDER BY e.FullName;
END
GO
